name: CD

on:
  push:
    branches: ["master", "main"]

concurrency:
  group: cd-${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

env:
  PYTHON_VERSION: 3.11
  POETRY_VERSION: 1.8.2

jobs:
  tests:
    uses: ./.github/workflows/ci.yml

  build:
    name: "Inspector Build"
    runs-on: ubuntu-latest
    needs: tests
    steps:
      - uses: actions/checkout@v4
      - uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - uses: docker/setup-buildx-action@v2
      - uses: docker/build-push-action@v4
        with:
          context: .
          file: ./docker/prod/Dockerfile
          push: true
          tags: |
            ${{ secrets.DOCKERHUB_USERNAME }}/inspector:${{ github.sha }}
            ${{ secrets.DOCKERHUB_USERNAME }}/inspector:latest
          cache-from: type=gha
          cache-to: type=gha,mode=max

  deploy:
    name: "Inspector Deploy"
    runs-on: ubuntu-latest
    needs: build
    steps:
      - uses: actions/checkout@v4
      - uses: appleboy/ssh-action@v1.0.0  # deploy app using ssh
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USERNAME }}
          key: ${{ secrets.EC2_KEY }}
          script: |
            docker stop inspector || true
            docker rm inspector || true
            docker pull ${{ secrets.DOCKERHUB_USERNAME }}/inspector:latest
            ./run_inspector
